export const siteConfig = {
  name: "Solve With Software",
  tagline: "Insights on Software Development, AI, and Digital Transformation",
  heroTitle: "Your Developer. Your Project.",
  heroSubtitle: "From idea to launch, together.",
  description:
    "Expert insights on software development, AI, automation, and digital transformation. Practical advice for businesses navigating technology decisions.",
  url: "https://solvewithsoftware.com",
  ogImage: "https://solvewithsoftware.com/images/og/default.jpg",
  twitterHandle: "@solvewithsw",
  email: "hello@solvewithsoftware.com",
  phone: "01206-848428",
  foundingDate: "2012",
  keywords: [
    "software development",
    "mobile app development",
    "web applications",
    "business automation",
    "digital transformation",
    "AI solutions",
    "Flutter development",
    "Next.js development",
    ".NET development",
    "custom software",
    "UK software company",
    "tech blog",
    "software insights",
  ],
};
